# Generated by Django 3.0.3 on 2020-02-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0003_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='reisi',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='hello_app.Flight'),
        ),
    ]
